### ISSUE TITLE
AOS fade left and right on mobile responsiveness

### ISSUE THREAD

**Issue by joshuaeduards** [michalsnik/aos#234]
When using those, there will be a white space going to be appear on the right side that will cause unresponsiveness of the website.

**Comment by cedricengagor** [comment]
Have the same bug on my application, were you able to fix it?

**Comment by JESDslnt** [comment]
I removed the class fade left and right for now and used the up and down class.

**Comment by cedricengagor** [comment]
I fixed it with a simple overflow-x: hidden => In another issue on this page

**Comment by JESDslnt** [comment]
Oh great! Thanks.

**Comment by Gcamara14** [comment]
Are you supposed add this to the container element, or on the element itself?

**Comment by nirajrajgor** [comment]
When is the issue gonna solved by the author?

**Comment by ragboyjr** [comment]
@Gcamara14 I added it on the container element

```html
<div class="row text-center no-gutters" style="overflow-x: hidden">
    <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-right">...</div>
    <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-up">...</div>
    <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-left">...</div>
</div>
```

Worked great for me.

**Comment by michalsnik** [comment]
The solution with `overflow-x: hidden` is fine. I proposed it also in other issues. I'm not sure though it's something I want to add in global AOS styles. As I would probably need to add it on `body`. I think I'll just add  FAQ section in updated readme of upcoming v3.

**Comment by grasn** [comment]
It is still not fixed in the current version. The page width breaks and gets a bottom slider in the web-browser when using fade left/right. Thanks for the solution, it is still a working fix!

**Comment by JohnnyLeWebDeveloper** [comment]
Can confirm that this issue is still present when using fade-left and/or fade-right. Using overflow hidden does not appear to resolve this.

**Comment by nemoeric** [comment]
> I fixed it with a simple overflow-x: hidden => In another issue on this page

I love you. Thanks

**Comment by ghost** [comment]
My 'solution' was to make the with of the div with the data-aos attribute equal to auto (width: auto), so it wrapped around the text instead of wrapping around the entire element itself. I do, however, have to turn it off for tablet users because then the same issues occur. I wonder why the opacity is set to 0 instead of setting it to 0 then set the visibility to hidden in order to take out the elements 'presence' entirely. I feel that could fix this issue entirely!

**Comment by squareclouds** [comment]
hi guys,

overflow-x for the body was my first idea as well. i implemented it but still the same behaviour... after that i started googling and landed here :) for the people that got it working with overflow, how are your elemnts nested? i tried overflow for body and section (the section has 2 bootstrap columns that are animated from left-right), but still no luck.

@DylanPerez1 i am guessing if they are not visible some elements after the animated ones would just slide up, or parent divs wouldnt have the intended height, etc

EDIT: i can confirm that the overflow-x solution works on safari and firefow mobile IF i use it for the body and html tags. chrome mobile (ios) still shows the white space

**Comment by zeromh1810** [comment]
i have the same problem and i try to use overflow-x hidden to as well, but when i use it in the body a second scroll bar appeared :/. ¿does anyone has the same problem? ¿how can i fix it?.

**Comment by Haaidali** [comment]
> i have the same problem and i try to use overflow-x hidden to as well, but when i use it in the body a second scroll bar appeared :/. ¿does anyone has the same problem? ¿how can i fix it?.

Do this ====> <div class="row" style="overflow-x: hidden; overflow-y: hidden;">
It work for you.

**Comment by haaidrehman** [comment]
> i have the same problem and i try to use overflow-x hidden to as well, but when i use it in the body a second scroll bar appeared :/. ¿does anyone has the same problem? ¿how can i fix it?.

Do this ====> (div class="row" style="overflow-x: hidden; overflow-y: hidden;")
It will work for you.

**Comment by haaidrehman** [comment]
<div class="row" style="overflow-x: hidden; overflow-y: hidden;">
This will solve the problem in responsiveness.

**Comment by guido732** [comment]
I had the same issue, applying overflow-x on body didn't fix it (weirdly enough on firefox it looked good, I was having issues only on chrome after this)

Applying the overflow-x on the container of the AOS element solved it! (so far)

**Comment by saidbagherim** [comment]
Thank you mr.  Michalsnik

**Comment by ositaka** [comment]
`overflow-x: hidden` can be a problem when combining AOS with other plugins, for instance, the Smooth Scrollbar.

After reading the comment of @ragboyjr, I realized we can use just 2 classes for `.mobile` and for `.laptop`. I will paste down here the code I end up doing to solve this issue. I hope it can help more people in the future:

**CSS**
```
@media (max-width: 767px) {
    .laptop[data-aos] { display: none }
}

@media (min-width: 768px) {
    .mobile[data-aos] { display: none }
}
```

**HTML**
```
<div class="box">
    <div class="mobile" data-aos="fade-up">
        <img src="/assets/img/home-center-bg.jpg" alt="" />
    </div>
    <div class="laptop" data-aos="fade-left">
        <img src="/assets/img/home-center-bg.jpg" alt="" />
    </div>
</div>
```

You have to use **`.fade-up`** or **`.fade-down`** on mobile.

**Comment by AbdelrahmanAlaa360** [comment]
### Easiest solution
body {overflow: hidden}

**Comment by priyam-tongia** [comment]
Overflow-x , overflow-y and even overflow nothing is working for me. Tried everything!!

**Comment by Y1a2s3h4** [comment]
overflow-x : hidden is still working in 2020.

**Comment by Y1a2s3h4** [comment]
> Overflow-x , overflow-y and even overflow nothing is working for me. Tried everything!!

maybe you should try * {overflow-x: hidden}

**Comment by mkinberg** [comment]
I had the same issues in Chrome (mobile & tablet).  I found that overflow-x:hidden; fixed a few of my issues but not all.  I ended up changing the animation types to fix the outstanding white space margin problems.  The animations on my page that were causing issues were "zoom-out" and "fade-left".  This makes sense because the large elements on my page were being scaled/positioned outside of the viewfinder and then animated into place.  I discovered this because the white space margin   disappeared AFTER the animations finished.  I hope this helps someone :-)

**Comment by Joe-Powell** [comment]
put in your css

html,
body{
width:100%;
overflow-x:hidden;
}

**Comment by DevShaikh** [comment]
> @Gcamara14 I added it on the container element
> 
> ```
> <div class="row text-center no-gutters" style="overflow-x: hidden">
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-right">...</div>
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-up">...</div>
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-left">...</div>
> </div>
> ```
> 
> Worked great for me.

@ragboyjr Thanks Dude, you are a life saver!!

**Comment by aditya2305** [comment]
> put in your css
> 
> html,
> body{
> width:100%;
> overflow-x:hidden;
> }
Worked :)

**Comment by arrahmanbd** [comment]
Simply add those line on your stylesheet and see magic
```
* {
  margin: 0px;
  padding: 0px;
  overflow-x:unset;
} 
```

**Comment by Mesayan2027** [comment]
> Are you supposed add this to the container element, or on the element itself?

put it in the body works like a charm

**Comment by ichsanputr** [comment]
sure this solution works 100%

add this code n your file css

`html, body { overflow-x: hidden; }`

**Comment by ayush8385** [comment]
> @Gcamara14 I added it on the container element
> 
> ```
> <div class="row text-center no-gutters" style="overflow-x: hidden">
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-right">...</div>
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-up">...</div>
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-left">...</div>
> </div>
> ```
> 
> Worked great for me.

Thank you so much

**Comment by saleheen-dev** [comment]
This will work for sure,
Just add this code in your CSS file

html, body {
overflow-x: hidden;
}

**Comment by Henrique-Cabral-Omnix** [comment]
I have tried and the best possible approach (so far), was to add overflow-x: hidden to the container element of yout animations. For instance: 
`<div className="flex flex-col children-full-w pb-8 overflow-x-hidden">
      <Header data-aos-delay={150} data-aos="fade-left" />
      <main className="mt-10 flex flex-col">
        <section data-aos="zoom-in" className="my-8 flex flex-col">
          <HomeForm />
        </section>
      </main>
      <footer className="my-2 flex flex-col">
        <div data-aos="fade-left">Test</div>
      </footer>
</div>`

Thanks for the support guys.

**Comment by yanisahmed** [comment]
> I fixed it with a simple overflow-x: hidden => In another issue on this page

Its worked. Thank You

**Comment by meihu-ganesh** [comment]
It may be any 1D or 2D animation using aos, while in responsiveness you may see a bug of not displaying or anything, just add overflow: visible; in CSS under body{ } , this had worked for mee
`body {
    overflow: visible;
}`
Happy Coding :)``

**Comment by infrasolutions-web** [comment]
html, body { overflow-x: clip; } has fixed the white space issue. 
Had to use 'clip' iso. 'hidden' so that the navbar remains in sticky mode.

**Comment by stefanrows** [comment]
It should be mentioned in the official documentation that one has to use

`html, body {
overflow-x: hidden;
}`

to make this work on mobile.

**Comment by h1x0ver** [comment]
make it shorter like this 
<div style={{overflowY:'hidden', width:'100%' , overflowX:'hidden'}}>
            <div data-aos="fade-aos"
                 data-aos-duration="900">
                <HomeHeadBanner/>
            </div>
</div>

**Comment by h1x0ver** [comment]
overflow x,y hidden and w100% :)

**Comment by Owais3003** [comment]
.container, .container-fluid{
        overflow-x: hidden !important;
    }
it works try it.

**Comment by thealiyasar** [comment]
The solution to this problem is exactly as follows.

`html,
body { 
  overflow-x: hidden !important; 
  width: 100%; 
}`

**Comment by KT-Designer** [comment]
body,
html {
  overflow-x: hidden;
}

This approach can solve the issue.

**Comment by KT-Designer** [comment]
```
body,
html {
overflow-x: hidden;
}
```

This approach can solve the issue.

**Comment by xxotto** [comment]
This has been the only solution I found for my case using tailwind.

**Comment by desta** [comment]
i used @KT-Designer solution and because i using row from bootstrap i give too g-0

`<div class="row g-0">`

**Comment by Radiat09** [comment]
> Have the same bug on my application, were you able to fix it?



> I fixed it with a simple overflow-x: hidden => In another issue on this page

Thanks man that really helped me

**Comment by michaelreis-dev-br** [comment]
> @Gcamara14 I added it on the container element
> 
> ```
> <div class="row text-center no-gutters" style="overflow-x: hidden">
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-right">...</div>
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-up">...</div>
>     <div class="col-12 col-md-4 aos-init aos-animate" data-aos="fade-left">...</div>
> </div>
> ```
> 
> Worked great for me.

work for me

**Comment by mhgkhan** [comment]
I just resolve this issue at my portfolio today [Ghazna.dev](https://ghazna.vercel.app)

use `className="overflow-x-hidden"` if You are using tailwindsCSS otherwise use `section{
  overflow-x: hidden;
}`
